#include <allegro.h>
/* XPM */
static const char *allegico_xpm[] = {
/* columns rows colors chars-per-pixel */
"64 64 14 1 ",
"  c gray35",
". c #797D79",
"X c #519D39",
"o c #7DB66B",
"O c #9B9E9B",
"+ c #ACAEAC",
"@ c #D7D8D7",
"# c #D8DAD8",
"$ c #DADBDA",
"% c #DDDEDD",
"& c #D3E6CD",
"* c #DEEDDA",
"= c #F4F9F3",
"- c gray100",
/* pixels */
"----------------------------                  ------------------",
"--------------------------                     -----------------",
"--------------       ----                       ----------------",
"------------                                     -&&=-&&=-------",
"-----------                                       XX&-XX&-------",
"----------                                         X&-XX&-------",
"---------                                           &-XX&-------",
"--------                                            *-oo*-------",
"--------                                             -----------",
"-------                                              -----------",
"-------                                                     ----",
"-------                                                       --",
"-------                                                        -",
"-------                                                         ",
"-------                                                         ",
"-------                                                         ",
"-------                                                         ",
"-------                                                         ",
"-------                                                         ",
"------                                                          ",
"-----                                                           ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                               @",
"                                                              @@",
"                                                    #       @@@@",
"                                                    @@@$@#@#####",
"                       XXXXX                        @$###@#@#@##",
"                       XXXXXXXXXXXXX              X @#@@##@#@###",
"                       XXXXXXXXXXXXXXX           XX#############",
"                       XXXXXXXXXXXXXXXXX       XXXXX############",
"                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX##########",
"                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX#########",
"                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$@@$$$@$",
"                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$@$@$",
"                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$@$@$$",
"                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$",
"                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX$$$",
"                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"                       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"--                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"---                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"---                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"----                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"-----                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"------                     XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"-------                    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"--------                  %$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"---------               %$%%$XXXXXXXXXXXXXXXXXXXX%XXXXXXXXXXXXXX",
"-----------           %%%%%%%%XXXXXXXXXXXXXXXXXXX%%%%XXXXXXXXXXX",
"-------------       %%%%%%%%%%%XXXXXXXXXXXXXXXXX%%%%%%%%%%%XXXXX",
"-----------------O.+%%%%%%%%%%%%XXXXXXXXXXXXXXX%%%%%%%%%%%%%$%XX",
"-----------------O.+%%%%%%%%%%%%%XXXXXXXXXXXXX%%%%%%%%%%%%%%%%%%",
"-----------------O.+%%%%%%%%%%%%%%XXXXXXXXXXX%%%%%%%%%%%%%%%%%%%"
};

#if defined ALLEGRO_WITH_XWINDOWS && defined ALLEGRO_USE_CONSTRUCTOR
extern void *allegro_icon;
CONSTRUCTOR_FUNCTION(static void _set_allegro_icon(void));
static void _set_allegro_icon(void)
{
    allegro_icon = allegico_xpm;
}
#endif
